<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['services_app_description'] = 'Менеджер служб используется для контроля системных процессов и их состояния работы, предоставляет полезный обзор. Вы можете управлять службами, которые будут запускаться во время загрузки.';
$lang['services_app_name'] = 'Менеджер служб';
$lang['services_boot_status'] = 'Запущено';
$lang['services_description'] = 'Описание службы';
$lang['services_service'] = 'Службы';
$lang['services_services'] = 'Службы';
