<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['services_app_description'] = 'The Services app is used to control the system daemons and their running state and provides a useful overview. You can also control which services start up at boot time.';
$lang['services_app_name'] = 'Services';
$lang['services_boot_status'] = 'Startup';
$lang['services_description'] = 'Service Description';
$lang['services_service'] = 'Service';
$lang['services_services'] = 'Services';
